### ISSUE TITLE
Weird French TTS when error event is caught

### ISSUE THREAD

**Issue by wolfy** [nuance-communications/mix-demo-client-azstaticwebapps#102]
I tried the Demo Client and for some reason the message that is playing out is clearly trying to play in French (using a multilingual voice Amelie-Ml. See recording: https://nuancecommunications-my.sharepoint.com/:v:/g/personal/boris_volfson_nuance_com/EdNOtcG3fRBEsVTuHKVaD_gBv-yVdoUEMgF1Eq3gHvTdqw?e=BKGJu7

**Comment by wolfy** [comment]
Looking over this... Seems like Amelie is the default TTS voice for the project (which seems to override the voice set in demo client... is that right?). Also I guess defaults to French even though it's a multilingual voice.

**Comment by nirvanatikku** [comment]
@wolfy can you validate and close if not an issue? thx

**Comment by wolfy** [comment]
@nirvanatikku : I guess I am not sure if the project language should be overriding the TTS language that is set in the Demo client.

**Comment by wolfy** [comment]
@nirvanatikku : Cool closing.
