### ISSUE TITLE
ASRaaS - cannot change language

### ISSUE THREAD

**Issue by mitchwarner** [nuance-communications/mix-demo-client-azstaticwebapps#106]
No matter what language you try to select on the ASRaaS page, it always keeps US English selected.

**Comment by nirvanatikku** [comment]
+ visualizer regressed with latest

**Comment by mitchwarner** [comment]
@nirvanatikku do we know when this fix will be merged into the live version of https://demo.mix.nuance.com/app/? Currently I am still seeing the same issue.
