### ISSUE TITLE
Log Events Table link results in window content resize

### ISSUE THREAD

**Issue by jonwmccain-nuance** [nuance-communications/mix-demo-client-azstaticwebapps#82]
While in an active DLGaaS session clicking the link for "Log Events Table" it zooms in REAL far and you go from this:
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/78501531/178055935-251a80b6-af31-414c-b899-b80b7b9a13d4.png)

to this:
 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78501531/178055940-8b713324-4b8c-44fc-9765-2d2fa65d24f2.png)

**Comment by nirvanatikku** [comment]
Found the issue. Relates to the large payloads coming back in certain events. Fix coming soon.

**Comment by jonwmccain-nuance** [comment]
Awesome!!!

Jon W. McCain
(he/him)
Principal Sales Engineer, Enterprise
Nuance Communications

***@***.******@***.***>

Amplify your ability to help others™

[Logo]<http://www.nuance.com/>

Upcoming out of office:

LinkedIn<https://www.linkedin.com/company/nuance-communications/> | YouTube<https://www.youtube.com/nuanceinc> | Facebook<https://www.facebook.com/nuancecommunications/> | Instagram<https://www.instagram.com/nuancecommunications/> | Twitter<https://twitter.com/NuanceInc>

From: Nirvana Tikku ***@***.***>
Sent: Thursday, October 6, 2022 3:15 PM
To: nuance-communications/mix-demo-client-azstaticwebapps ***@***.***>
Cc: McCain, Jon ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [nuance-communications/mix-demo-client-azstaticwebapps] Log Events Table link results in window content resize (Issue #82)

CAUTION: This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments.
________________________________

Found the issue. Relates to the large payloads coming back in certain events. Fix coming soon.
